/**:
    ros__parameters:
        image_transport: raw    # image format
        families: [Custom48h12, 36h11]        # list of tag families (e.g. [36h11, Custom48h12])
        families_sizes: [0.12, 0.037]          # tag size for each family (must match families array length)
        size: 0.12             # tag edge size in meter (fallback if family not in families_sizes)
        max_hamming: 0          # maximum allowed hamming distance (corrected bits)

        # see "apriltag.h" 'struct apriltag_detector' for more documentation on these optional parameters
        detector:
            threads: 1          # number of threads
            decimate: 2.0       # decimate resolution for quad detection
            blur: 0.0           # sigma of Gaussian blur for quad detection
            refine: True        # snap to strong gradients
            sharpening: 0.25    # sharpening of decoded images
            debug: False        # write additional debugging images to current working directory


        pose_estimation_method: "pnp"   # method for estimating the tag pose

        # optional list of tags
